# Generated by Django 5.1.5 on 2025-10-02 10:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_student_choosing_lesson_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(error_messages={'Enter a valid date.': 'نامعبتر'}, verbose_name='تاریخ تولد'),
        ),
    ]
