# Generated by Django 5.1.5 on 2025-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_group_created_group_modified_lesson_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='address',
            field=models.TextField(default='test', verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='professor',
            name='marriage',
            field=models.BooleanField(default=False, verbose_name='وضعیت تاهل'),
        ),
    ]
