# Generated by Django 5.1.5 on 2025-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_professor_address_professor_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='professor_major',
            new_name='major',
        ),
    ]
