# Generated by Django 5.1.5 on 2025-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_lesson_day_lesson_class_class_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='class_end_time',
            field=models.TimeField(max_length=5, verbose_name='ساعت پایان کلاس'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='class_start_time',
            field=models.TimeField(max_length=5, verbose_name='ساعت شروع کلاس'),
        ),
    ]
