# Generated by Django 5.1.5 on 2025-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_lesson_class_class_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='class_day',
            field=models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یک شنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه')], default='شنبه', max_length=10, verbose_name='روز برگزاری کلاس'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='degree',
            field=models.CharField(blank=True, choices=[('کارشناسی', 'کارشناسی'), ('ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=8, verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('پیوسته', 'پیوسته'), ('ناپیوسته', 'ناپیوسته')], default='پیوسته', max_length=8, verbose_name='نوع مقطع'),
        ),
    ]
