# Generated by Django 5.1.5 on 2025-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_lesson_class_class_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('اصلی', 'اصلی'), ('پایه', 'پایه'), ('عمومی', 'عمومی'), ('تخصصی', 'تخصصی'), ('اختیاری', 'اختیاری')], default='اصلی', max_length=9, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('نظری', 'نظری'), ('نظری-عملی', 'نظری - عملی'), ('عملی', 'عملی'), ('آز', 'آزمایشگاهی'), ('کارآموزی', 'کارآموزی')], default='نظری', max_length=11, verbose_name='نوع واحد'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5, verbose_name='وضعیت تحصیل'),
        ),
    ]
