# Generated by Django 5.1.5 on 2025-11-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_lesson_lesson_type_alter_lesson_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('asli', 'اصلی'), ('paye', 'پایه'), ('omomi', 'عمومی'), ('takhasosi', 'تخصصی'), ('ekhtiari', 'اختیاری')], default='asli', max_length=11, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('nazari', 'نظری'), ('nazari-amali', 'نظری - عملی'), ('amali', 'عملی'), ('lab', 'آزمایشگاهی'), ('internship', 'کارآموزی')], default='nazari', max_length=12, verbose_name='نوع واحد'),
        ),
    ]
