# Generated by Django 5.1.5 on 2025-11-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_lesson_lesson_type_alter_lesson_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('اصلی', 'اصلی'), ('پایه', 'پایه'), ('عمومی', 'عمومی'), ('تخصصی', 'تخصصی'), ('اختیاری', 'اختیاری')], default='اصلی', max_length=9, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('نظری', 'نظری'), ('نظری-عملی', 'نظری - عملی'), ('عملی', 'عملی'), ('آز', 'آزمایشگاهی'), ('کارآموزی', 'کارآموزی')], default='نظری', max_length=11, verbose_name='نوع واحد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default='111111111111', max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی'),
        ),
    ]
