# Generated by Django 5.1.5 on 2026-02-22 15:21

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('code', models.CharField(default='1111111111', max_length=10, primary_key=True, serialize=False, verbose_name='کد درس')),
                ('unit', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد واحد')),
                ('unit_type', models.CharField(blank=True, choices=[('نظری', 'نظری'), ('نظری-عملی', 'نظری - عملی'), ('عملی', 'عملی'), ('آز', 'آزمایشگاهی'), ('کارآموزی', 'کارآموزی')], default='نظری', max_length=11, verbose_name='نوع واحد')),
                ('lesson_type', models.CharField(blank=True, choices=[('اصلی', 'اصلی'), ('پایه', 'پایه'), ('عمومی', 'عمومی'), ('تخصصی', 'تخصصی'), ('اختیاری', 'اختیاری')], default='اصلی', max_length=9, verbose_name='نوع درس')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('student_number', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=10)),
                ('hamniaz', models.ManyToManyField(blank=True, to='LessonsApp.lesson', verbose_name='هم نیاز')),
                ('lesson_major', models.ManyToManyField(to='academic.major', verbose_name='رشته')),
                ('pishniaz', models.ManyToManyField(blank=True, to='LessonsApp.lesson', verbose_name='پیش نیاز')),
            ],
        ),
        migrations.CreateModel(
            name='lesson_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یک شنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه')], default='شنبه', max_length=10, verbose_name='روز برگزاری کلاس')),
                ('class_start_time', models.TimeField(max_length=5, verbose_name='ساعت شروع کلاس')),
                ('class_end_time', models.TimeField(max_length=5, verbose_name='ساعت پایان کلاس')),
                ('degree', models.CharField(blank=True, choices=[('کارشناسی', 'کارشناسی'), ('ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=8, verbose_name='مقطع')),
                ('degree_type', models.CharField(blank=True, choices=[('پیوسته', 'پیوسته'), ('ناپیوسته', 'ناپیوسته')], default='پیوسته', max_length=8, verbose_name='نوع مقطع')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('class_code', models.PositiveSmallIntegerField(verbose_name='کد ارائه')),
                ('class_number', models.PositiveSmallIntegerField(verbose_name='شماره کلاس')),
                ('semester', models.PositiveSmallIntegerField(blank=True, default='1111', verbose_name='نیمسال')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.group', verbose_name='نام گروه')),
                ('lesson_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='LessonsApp.lesson', verbose_name='نام درس')),
            ],
        ),
    ]
