# Generated by Django 5.1.5 on 2026-02-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LessonsApp', '0001_initial'),
        ('ProfessorsApp', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_class',
            name='professor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ProfessorsApp.professor', verbose_name='نام استاد'),
        ),
        migrations.AddField(
            model_name='lesson_class',
            name='university_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.university', verbose_name='مکان برگزاری'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['code'], name='LessonsApp__code_f2a4de_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson_class',
            index=models.Index(fields=['class_code', 'semester'], name='LessonsApp__class_c_94831c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson_class',
            constraint=models.UniqueConstraint(fields=('class_code', 'semester'), name='unique_ClassCode_semester'),
        ),
    ]
