# Generated by Django 5.1.5 on 2026-02-23 14:41

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_class',
            name='exam_date_time',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان و تاریخ امتحان'),
        ),
    ]
