# Generated by Django 5.1.5 on 2026-02-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0003_lesson_class_exam_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student_number',
        ),
    ]
