# Generated by Django 5.1.5 on 2026-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0004_remove_lesson_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='exam_date_time',
            field=models.CharField(max_length=15, null=True, verbose_name='زمان و تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, default=4042, verbose_name='نیمسال'),
        ),
    ]
