# Generated by Django 5.1.5 on 2026-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0005_alter_lesson_class_exam_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='exam_date_time',
            field=models.CharField(max_length=16, null=True, verbose_name='زمان و تاریخ امتحان'),
        ),
    ]
