# Generated by Django 5.1.5 on 2026-02-24 16:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0006_alter_lesson_class_exam_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='exam_date_time',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان و تاریخ امتحان'),
        ),
    ]
