# Generated by Django 5.1.5 on 2026-02-25 15:00

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LessonsApp', '0007_alter_lesson_class_exam_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_class',
            name='exam_date_time',
            field=django_jalali.db.models.jDateTimeField(default='1411-11-11 11:11', verbose_name='زمان و تاریخ امتحان'),
            preserve_default=False,
        ),
    ]
