# Generated by Django 5.1.5 on 2026-02-22 15:21

import StudentsApp.models
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LessonsApp', '0001_initial'),
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=StudentsApp.models.student.image_saving_location, verbose_name='عکس')),
                ('marriage', models.BooleanField(default=False, verbose_name='وضعیت تاهل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('student_number', models.CharField(default='111111111111', max_length=12, primary_key=True, serialize=False, verbose_name='شماره دانشجویی')),
                ('entrance_year', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='سال ورودی')),
                ('last_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='آخرین سال تحصیل')),
                ('role', models.CharField(default='student', max_length=10)),
                ('status', models.CharField(blank=True, choices=[('فارغ', 'فارغ التحصیل'), ('مشغول', 'مشغول به تحصیل'), ('مرخصی', 'مرخصی')], default='مشغول', max_length=5, verbose_name='وضعیت تحصیل')),
                ('major', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='academic.major', verbose_name='رشته')),
                ('university', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student', to='academic.university', verbose_name='دانشگاه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_choosing_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField(default=0, verbose_name='نیمسال')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتخاب')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('chosen_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='LessonsApp.lesson_class', verbose_name='درس')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='StudentsApp.student', verbose_name='دانشجو')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number', 'student_id'], name='StudentsApp_student_5661cc_idx'),
        ),
    ]
