# Generated by Django 5.1.5 on 2026-02-22 15:21

import ProfessorsApp.models
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LessonsApp', '0001_initial'),
        ('StudentsApp', '0001_initial'),
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='نمره')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='LessonsApp.lesson_class', verbose_name='درس')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='StudentsApp.student', verbose_name='دانشجو')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('first_name', models.CharField(max_length=70, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='جنسیت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('marriage', models.BooleanField(default=False, verbose_name='وضعیت تاهل')),
                ('professor_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=0.75, size=[1920, 1080], upload_to=ProfessorsApp.models.professor.image_saving_location, verbose_name='عکس')),
                ('major', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره موبایل')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('student_number', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=10)),
                ('code', models.CharField(default='1111111111', max_length=10, primary_key=True, serialize=False, verbose_name='کد استاد')),
                ('role', models.CharField(default='professor', max_length=10)),
                ('universities', models.ManyToManyField(related_name='professor', to='academic.university', verbose_name='دانشگاه(های) مشغول به تدریس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'professor_id'], name='ProfessorsA_code_d35edd_idx')],
            },
        ),
    ]
