# Generated by Django 5.1.5 on 2026-02-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='student_number',
        ),
    ]
