# Generated by Django 5.1.5 on 2026-04-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessorsApp', '0002_remove_professor_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='score',
            new_name='mark',
        ),
    ]
