# Generated by Django 5.1.5 on 2026-02-22 15:21

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('code', models.PositiveSmallIntegerField(default=0, verbose_name='کد گروه')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد رشته')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='academic_ma_code_87e885_idx')],
            },
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='نام دانشگاه')),
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد دانشگاه')),
                ('address', models.TextField(default='تهران', verbose_name='آدرس')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='academic_un_code_82e6fa_idx')],
            },
        ),
    ]
