# Generated by Django 5.1.5 on 2025-10-21 12:50

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True, verbose_name='کد ملی'),
        ),
    ]
