# Generated by Django 5.1.5 on 2025-10-22 12:14

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
