# Generated by Django 5.1.5 on 2025-10-22 12:21

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_student_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='major',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='major',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AddField(
            model_name='university',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
    ]
