# Generated by Django 5.1.5 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_professor_major_professor_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد واحد'),
        ),
    ]
