# Generated by Django 5.1.5 on 2025-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_lesson_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson_class',
            old_name='lesson_day',
            new_name='class_day',
        ),
        migrations.RemoveField(
            model_name='lesson_class',
            name='lesson_time',
        ),
        migrations.AddField(
            model_name='lesson_class',
            name='class_end_time',
            field=models.CharField(default='9:50', max_length=5, verbose_name='ساعت پایان کلاس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_class',
            name='class_start_time',
            field=models.CharField(default='8:00', max_length=5, verbose_name='ساعت شروع کلاس'),
            preserve_default=False,
        ),
    ]
