# Generated by Django 5.1.5 on 2025-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_lesson_lesson_type_alter_lesson_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.CharField(default='1111111111', max_length=10, primary_key=True, serialize=False, verbose_name='کد درس'),
        ),
        migrations.AlterField(
            model_name='lesson_class',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, default='1111', verbose_name='نیمسال'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(default='1111111111', max_length=10, primary_key=True, serialize=False, verbose_name='کد استاد'),
        ),
    ]
